export default {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  ENABLE_LOADING: 'ENABLE_LOADING',
  DISABLE_LOADING: 'DISABLE_LOADING',
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_ARTICLES: 'SET_ARTICLES',
  SET_PAGES: 'SET_PAGES',
  UPDATE_SEARCH_QUERY: 'UPDATE_SEARCH_QUERY',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT'
}
